export const FETCH_COMMENTS: string = "FETCH_COMMENTS";
export const RECIEVE_COMMENTS: string = "RECIEVE_COMMENTS";
export const FETCH_COMMENTS_ERROR: string = "FETCH_COMMENTS_ERROR";
export const DELETE_COMMENT: string = "DELETE_COMMENT";
export const DELETE_COMMENT_ERROR: string = "DELETE_COMMENT_ERROR";